[package]
name = "WASM_SNAKE"
version = "0.1.0"
author = "Rusty Boy"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

stdweb = "0.4.20"

